import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, ArrowLeft, Banknote, Building2, ChevronRight, CircleDot, Landmark, ReceiptText, Search, ShieldCheck, WalletCards } from 'lucide-react'
import { useMemo, useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { apiGet, operatorErrorMessage } from '@/lib/api'
import { cn } from '@/lib/utils'
import { canUseUi } from '@/components/laundry/LaundryShell'
import VisualEmptyState from '@/components/laundry/VisualEmptyState'
import VisualLoadingState from '@/components/laundry/VisualLoadingState'

type PlatformStatus = { configured: boolean; connected: boolean }
type Vendor = { id: string; name?: string; commission_rate?: string | number; is_active?: boolean; payout_bank_ready?: boolean }
type FinancialPeriod = { id: string; period_type?: string; period_start?: string; period_end?: string; gross_revenue?: string | number; net_revenue?: string | number; platform_commission?: string | number; payout_amount?: string | number; payout_status?: string; failure_reason?: string | null }
type Transaction = { id: string; type?: string; amount?: string | number; direction?: string; status?: string; description?: string | null; created_at?: string }
const rupees = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 })
function money(value?: string | number) { return rupees.format(Number(value || 0)) }
function label(value?: string | null) { return value ? value.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()) : 'Not recorded' }
function date(value?: string) { return value ? new Date(value).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Date unavailable' }
function payoutTone(status?: string) { return status === 'PAID' ? 'bg-[#e8f5ed] text-[#237449]' : status === 'HELD' ? 'bg-[#fff1ee] text-[#a4463f]' : status === 'PROCESSING' ? 'bg-[#edf2ff] text-[#4562b4]' : 'bg-[#fff5dd] text-[#8e6518]' }

export default function LaundryPlatformFinance() {
  const session = useQuery({ queryKey: ['auth-session'], queryFn: () => apiGet<{ user: { roles: string[] } | null }>('/auth/session') })
  const canAccess = canUseUi(session.data?.user?.roles, 'settings.manage')
  const connection = useQuery({ queryKey: ['platform-status'], queryFn: () => apiGet<PlatformStatus>('/platform/status'), enabled: canAccess })
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState<string>()
  const query = useMemo(() => new URLSearchParams(Object.entries({ ...(search.trim() ? { search: search.trim() } : {}), page: '1', limit: '50' })).toString(), [search])
  const vendors = useQuery({ queryKey: ['platform-finance-vendors', query], queryFn: () => apiGet<Vendor[]>(`/platform/finance/vendors?${query}`), enabled: canAccess && Boolean(connection.data?.connected), staleTime: 10_000 })
  const selectedVendor = (vendors.data || []).find((vendor) => vendor.id === selected)
  const financials = useQuery({ queryKey: ['platform-finance-periods', selected], queryFn: () => apiGet<FinancialPeriod[]>(`/platform/finance/vendors/${encodeURIComponent(selected!)}/financials?page=1&limit=20`), enabled: Boolean(selected) && canAccess && Boolean(connection.data?.connected), staleTime: 10_000 })
  const transactions = useQuery({ queryKey: ['platform-finance-transactions', selected], queryFn: () => apiGet<Transaction[]>(`/platform/finance/vendors/${encodeURIComponent(selected!)}/transactions?page=1&limit=20`), enabled: Boolean(selected) && canAccess && Boolean(connection.data?.connected), staleTime: 10_000 })

  if (session.isLoading || connection.isLoading) return <VisualLoadingState title="Preparing platform finance" detail="Checking the local permission and platform-admin connection." icon={Landmark} />
  if (!canAccess) return <VisualEmptyState kind="orders" title="Not available" detail="Platform finance oversight is limited to store owners on this installation." />
  if (!connection.data?.connected) return <VisualEmptyState kind="orders" title="Connect a platform-admin account first" detail="Vendor settlement evidence remains in the cloud. Connect the separate administrator identity before reviewing it." action={<Link to="/laundry/platform-control" className="inline-flex items-center gap-2 rounded-xl bg-[#193d48] px-3 py-2 text-xs font-bold text-white"><ShieldCheck className="h-3.5 w-3.5" />Open Platform Control</Link>} />

  const periods = financials.data || []
  const held = periods.filter((period) => period.payout_status === 'HELD').length
  const latest = periods[0]
  return <div className="animate-in fade-in slide-in-from-bottom-2 duration-500">
    <header className="relative overflow-hidden rounded-[26px] border border-[#193d48]/20 bg-[radial-gradient(circle_at_86%_0%,rgba(243,193,97,.22),transparent_28%),linear-gradient(135deg,#102d37,#245663)] px-5 py-6 text-white shadow-[0_18px_48px_rgba(25,61,72,.18)] md:px-7"><div className="relative flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><Link to="/laundry/platform-control" className="inline-flex items-center gap-1.5 text-xs font-bold text-[#cfe4e7] hover:text-white"><ArrowLeft className="h-3.5 w-3.5" />Platform Control</Link><p className="mt-4 text-[10px] font-extrabold uppercase tracking-[.2em] text-[#b5d9d5]">Platform finance oversight</p><h1 className="mt-2 font-display text-3xl font-extrabold tracking-[-.04em] md:text-4xl">Settlement evidence, without false certainty.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#d8ecec]">Read the cloud ledger and financial periods here. Bank details, release controls, and manual “paid” actions stay unavailable until a real provider supplies payment evidence.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs font-bold"><CircleDot className="h-3.5 w-3.5 text-[#ffd37d]" />Cloud read-only</span></div></header>
    <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(300px,.8fr)_minmax(0,1.7fr)]"><aside className="overflow-hidden rounded-[22px] border border-[#193d48]/10 bg-white shadow-[0_10px_30px_rgba(25,61,72,.045)]"><div className="border-b border-[#193d48]/8 p-3"><div className="flex items-center gap-2 rounded-xl border border-[#193d48]/10 bg-[#fbfcfc] px-3 py-2"><Search className="h-4 w-4 text-[#39727b]" /><label htmlFor="platform-finance-search" className="sr-only">Find a vendor</label><input id="platform-finance-search" value={search} onChange={(event) => { setSearch(event.target.value); setSelected(undefined) }} placeholder="Find vendor" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#98a5a8]" /></div></div><div className="flex items-center justify-between px-4 py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#718087]">Vendor settlement view</p><p className="mt-0.5 text-sm font-semibold text-[#27454c]">{vendors.isLoading ? 'Loading vendors' : `${vendors.data?.length || 0} visible vendor${(vendors.data?.length || 0) === 1 ? '' : 's'}`}</p></div><Building2 className="h-4 w-4 text-[#8b9a99]" /></div>{vendors.isLoading ? <div className="p-5"><VisualLoadingState title="Reading vendor finance" detail="The platform backend remains the financial authority." icon={Landmark} /></div> : vendors.isError ? <ErrorNotice error={vendors.error} fallback="Vendor settlement visibility could not be read." /> : vendors.data?.length ? <div className="divide-y divide-[#193d48]/8">{vendors.data.map((vendor) => <button key={vendor.id} type="button" onClick={() => setSelected(vendor.id)} className={cn('flex w-full items-center gap-3 px-4 py-3.5 text-left transition hover:bg-[#f8fbfb]', selected === vendor.id && 'bg-[#eff7f7]')}><span className={cn('grid h-9 w-9 shrink-0 place-items-center rounded-xl', vendor.payout_bank_ready ? 'bg-[#e7f4ec] text-[#27704a]' : 'bg-[#fff2e8] text-[#b26132]')}>{vendor.payout_bank_ready ? <Landmark className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold text-[#294d57]">{vendor.name || 'Unnamed vendor'}</span><span className="mt-0.5 block text-[11px] text-[#718087]">{vendor.payout_bank_ready ? 'Payout bank details recorded' : 'Payout bank details incomplete'} · {vendor.is_active ? 'Active' : 'Inactive'}</span></span><ChevronRight className="h-4 w-4 text-[#6e8a90]" /></button>)}</div> : <VisualEmptyState kind="orders" title="No vendors match" detail="Try another vendor name. This list is read from the live platform finance directory." />}</aside>
      <main className="min-w-0">{!selected ? <VisualEmptyState kind="orders" title="Choose a vendor to inspect" detail="Select a vendor to see cloud-owned financial periods and their append-only ledger entries." /> : <><section className="rounded-[22px] border border-[#193d48]/10 bg-white p-4 shadow-[0_10px_30px_rgba(25,61,72,.045)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#6d8a91]">Selected vendor</p><h2 className="mt-1 text-xl font-extrabold tracking-[-.03em] text-[#193d48]">{selectedVendor?.name || 'Vendor finance'}</h2><p className="mt-1 text-xs text-[#6e8085]">Commission {selectedVendor?.commission_rate ?? 'not recorded'}% · {selectedVendor?.payout_bank_ready ? 'Bank readiness confirmed' : 'Bank readiness needs attention'}</p></div><span className={cn('inline-flex w-fit items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-extrabold', latest ? payoutTone(latest.payout_status) : 'bg-[#edf2f2] text-[#5c7277]')}><CircleDot className="h-3 w-3" />{latest ? `Latest: ${label(latest.payout_status)}` : 'No period yet'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric icon={WalletCards} label="Latest net revenue" value={latest ? money(latest.net_revenue) : '—'} /><Metric icon={Banknote} label="Latest payout amount" value={latest ? money(latest.payout_amount) : '—'} /><Metric icon={AlertTriangle} label="Held periods" value={String(held)} tone={held ? 'amber' : 'green'} /></div></section>
      <section className="mt-4 grid gap-4 2xl:grid-cols-2"><DataPanel icon={ReceiptText} title="Financial periods" subtitle="Cloud-calculated revenue, commission and payout state" loading={financials.isLoading} error={financials.error} empty="No financial periods are available for this vendor." >{periods.map((period) => <article key={period.id} className="rounded-xl border border-[#193d48]/9 bg-[#fbfcfc] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-[#284a53]">{label(period.period_type)} · {date(period.period_start)} – {date(period.period_end)}</p><p className="mt-1 text-xs text-[#6e8186]">Gross {money(period.gross_revenue)} · Platform fee {money(period.platform_commission)}</p></div><span className={cn('inline-flex shrink-0 items-center gap-1 rounded-full px-2 py-1 text-[10px] font-extrabold', payoutTone(period.payout_status))}><CircleDot className="h-3 w-3" />{label(period.payout_status)}</span></div><div className="mt-3 flex items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#789095]">Vendor net</p><p className="mt-1 text-lg font-extrabold text-[#193d48]">{money(period.net_revenue)}</p></div><div className="text-right"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#789095]">Payout</p><p className="mt-1 text-sm font-extrabold text-[#284a53]">{money(period.payout_amount)}</p></div></div>{period.failure_reason ? <p className="mt-3 rounded-lg bg-[#fff3ed] px-2.5 py-2 text-[11px] font-semibold text-[#a85536]">{period.failure_reason}</p> : null}</article>)}</DataPanel>
      <DataPanel icon={ReceiptText} title="Ledger evidence" subtitle="Most recent cloud-owned settlement entries" loading={transactions.isLoading} error={transactions.error} empty="No ledger entries are available for this vendor." >{(transactions.data || []).map((transaction) => <article key={transaction.id} className="flex items-start gap-3 rounded-xl border border-[#193d48]/9 bg-[#fbfcfc] p-3"><span className={cn('mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg', transaction.direction === 'DEBIT' ? 'bg-[#fff0ed] text-[#a4463f]' : 'bg-[#e8f5ed] text-[#237449]')}><ReceiptText className="h-3.5 w-3.5" /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="truncate text-sm font-bold text-[#284a53]">{label(transaction.type)}</p><p className="shrink-0 text-sm font-extrabold text-[#193d48]">{transaction.direction === 'DEBIT' ? '−' : '+'}{money(transaction.amount)}</p></div><p className="mt-1 truncate text-xs text-[#6e8186]">{transaction.description || label(transaction.status)} · {date(transaction.created_at)}</p></div></article>)}</DataPanel></section>
      <p className="mt-4 flex items-start gap-2 rounded-xl border border-[#e7d39c] bg-[#fff9e9] px-3 py-3 text-xs leading-5 text-[#73561d]"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />A paid status requires real provider evidence. This read-only view cannot release a payout, alter bank information, or mark a period paid.</p></>}</main></section>
  </div>
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof Landmark; label: string; value: string; tone?: 'amber' | 'green' }) { return <article className="rounded-xl border border-[#193d48]/9 bg-[#fbfcfc] p-3"><Icon className={cn('h-4 w-4', tone === 'amber' ? 'text-[#b17420]' : tone === 'green' ? 'text-[#27704a]' : 'text-[#39727b]')} /><p className="mt-3 text-[10px] font-extrabold uppercase tracking-[.11em] text-[#789095]">{label}</p><p className="mt-1 text-lg font-extrabold tracking-[-.03em] text-[#193d48]">{value}</p></article> }
function DataPanel({ icon: Icon, title, subtitle, loading, error, empty, children }: { icon: typeof ReceiptText; title: string; subtitle: string; loading: boolean; error: unknown; empty: string; children: ReactNode }) { const hasChildren = Array.isArray(children) && children.length > 0; return <section className="overflow-hidden rounded-[22px] border border-[#193d48]/10 bg-white shadow-[0_10px_30px_rgba(25,61,72,.045)]"><header className="flex items-start gap-3 border-b border-[#193d48]/8 px-4 py-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eaf4f4] text-[#287079]"><Icon className="h-4 w-4" /></span><div><h3 className="text-sm font-extrabold text-[#284a53]">{title}</h3><p className="mt-0.5 text-xs text-[#718087]">{subtitle}</p></div></header>{loading ? <div className="p-5"><VisualLoadingState title={`Reading ${title.toLowerCase()}`} detail="This information remains cloud-authoritative." icon={ReceiptText} /></div> : error ? <ErrorNotice error={error} fallback={`${title} could not be read.`} /> : hasChildren ? <div className="space-y-2 p-3">{children}</div> : <VisualEmptyState kind="orders" title="Nothing recorded" detail={empty} />}</section> }
function ErrorNotice({ error, fallback }: { error: unknown; fallback: string }) { return <div role="alert" className="m-4 flex items-start gap-2 rounded-xl bg-[#fde9e6] px-3 py-2.5 text-sm text-[#a44036]"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />{operatorErrorMessage(error, fallback)}</div> }
